language: shell
services: docker

env:
  - VARIANT=apache
  - VARIANT=fpm
  - VARIANT=fpm-alpine

before_script:
  - env | sort
  - cd "$VARIANT"
  - BASE="jakejarvis/wordpress-beta"
  - IMAGE="${BASE}:${VARIANT}"

script:
  - docker build -t "$IMAGE" .
  - docker images

notifications:
  email: false
